name: resuable deploy
on: 
  workflow_call:
      inputs:
        artifact-name:
          description: 'The name of the artifact to download'
          required: false
          type: string
          default: 'dist'
      # secrets:
      #   some-secret:
      #     required: false
      outputs:
        result:
          description: 'The result of the deploy step'
          value: ${{ jobs.deploy.outputs.outcome }}

jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result}}
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls -la
      - name: Output Information
        run: echo "deploying & uploading"
      - name: Set result output
        id: set-result
        run: echo "::set-output name=step-result::success"